### ISSUE TITLE
🐛 |  Exception when having kotlin function annotated with @KChutney

### ISSUE THREAD

**Issue by iguissouma** [chutney-testing/chutney-idea-plugin#17]
### What happened?

methods annotated with @KChutney shwos error and block code analysis for kotlin

annotation class KChutney()

@KChutney
fun `my test`() =
    Scenario(id = 1, title = "my title") {

    }

### Steps to reproduce

Open a kotlin file with a function annotated with @KChutney

### Relevant logs and/or screenshots/GIFs

```shell
java.lang.NoSuchMethodError: 'boolean org.jetbrains.kotlin.idea.util.PsiUtilsKt.hasAnnotationWithShortName$default(org.jetbrains.kotlin.psi.KtAnnotated, java.lang.String, org.jetbrains.kotlin.descriptors.annotations.AnnotationUseSiteTarget, int, java.lang.Object)'
	at com.chutneytesting.idea.ChutneyUtil.isChutneyDslMethod(ChutneyUtil.kt:60)
	at com.chutneytesting.idea.runner.ChutneyKotlinLineMarkerProvider.getLineMarkerInfo(ChutneyKotlinLineMarkerProvider.kt:11)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.queryProviders(LineMarkersPass.java:184)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.lambda$doCollectInformation$3(LineMarkersPass.java:104)
	at com.intellij.codeInsight.daemon.impl.Divider.divideInsideAndOutsideInOneRoot(Divider.java:95)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.doCollectInformation(LineMarkersPass.java:99)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:57)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$1(PassExecutorService.java:405)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1086)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:397)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:591)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:666)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:622)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:590)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:396)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:372)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:174)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:182)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:370)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:181)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
```

### Possible fixes

```shell
disable running kotlin function features or upgrade to latest sdk
```

### Version

2.3

### What OS did you use?

Windows

**Comment by KarimGl** [comment]
Could not reproduce in Version 2.4

**Comment by nbrouand** [comment]
Waiting for Issam check
